### ISSUE TITLE
[BUG] Changing the redis port to another port does not work properly

### ISSUE THREAD

**Issue by taoyao-code** [openimsdk/openim-docker#148]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

.env
```
# Redis configuration
REDIS_ADDRESS="redis_7:6379"                 # Address of Redis server
```

docker-composer
```
  redis:
    image: "${REDIS_IMAGE}"
    container_name: redis_7
    ports:
      - "16379:6379"
    volumes:
      - "${DATA_DIR}/components/redis/data:/data"
      - "${DATA_DIR}/components/redis/config/redis.conf:/usr/local/redis/config/redis.conf"
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: [ "redis-server", "/usr/local/redis/config/redis.conf", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]
    networks:
      - openim

```

### Screenshots Link

<img width="1137" alt="image" src="https://github.com/openimsdk/openim-docker/assets/38855041/6e8a2d2b-8f4f-490e-89de-05c31eba9294">
