### ISSUE TITLE
Bug: Mysql cannot change userame root

### ISSUE THREAD

**Issue by AndrewZuo01** [openimsdk/openim-docker#64]
### What happened?

I change the user name in .env file, then when I register user it has error

### What did you expect to happen?

it shouldn't have error

### How can we reproduce it (as minimally and precisely as possible)?

change the user name root to root1 in .env file, then register user at port 11001

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
fix docker-compose file, add:
```
version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
    user: "1000:1000"  # 指定非 root 用户的 UID 和 GID

volumes:
  my-db:

```

**Comment by kubbot** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
fix docker-compose file, add:
```
version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
    user: "1000:1000" # Specify the UID and GID of the non-root user

volumes:
  my-db:

```
