### ISSUE TITLE
Bug: Cannot change OPENIM_ADMIN_API_PORT

### ISSUE THREAD

**Issue by AndrewZuo01** [openimsdk/openim-docker#69]
### What happened?

cannot change OPENIM_ADMIN_API_PORT, cannot login admin dashboard

### What did you expect to happen?

able to log in admin dashboard

### How can we reproduce it (as minimally and precisely as possible)?

change OPENIM_ADMIN_API_PORT to 40009 and then run code

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
fix docker-compose file, add:
```
version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
    user: "1000:1000"  # 指定非 root 用户的 UID 和 GID

volumes:
  my-db:

```

**Comment by kubbot** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
fix docker-compose file, add:
```
version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
    user: "1000:1000" # Specify the UID and GID of the non-root user

volumes:
  my-db:

```
